name: Release

on:
  push:
    tags:        
      - 'ui-*.*.*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v3
          with:
            version: 8

        - name: Setup Node.js 18.x
          uses: actions/setup-node@v4
          with:
            node-version: 18.x
            registry-url: https://npm.pkg.github.com

        - name: Install Dependencies
          run: pnpm i

        - name: Creating .npmrc
          run: |
            cat << EOF > "$HOME/.npmrc"
            dydfuf:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GH_REGISTRY_TOKEN
            EOF
          env:
            GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}

        - name: Publish to GitHub Package Registry
          run: pnpm publish packages/ui --access public --no-git-checks
          env:
            GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}