name: Node.js Package

on:
    push:
      tags:        
        - 'ui-*.*.*'
      branches:
        - 'feature/ui/raon-18-publish-package'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
    
      - uses: pnpm/action-setup@v3
        with:
            version: 8

      - run: pnpm install
      - run: pnpm build --filter=ui

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          registry-url: https://npm.pkg.github.com/
          scope: '@dydfuf'
      - uses: pnpm/action-setup@v3
        with:
            version: 8
      - run: pnpm install
      - run: npm publish --filter=ui --no-git-checks 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
